In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
tickers = ['CHFUSD=X', 'EURUSD=X', 'GBPUSD=X', 'JPY=X', 'CNY=X','UDOW', '000001.SS','CL=F', '^GSPC', '^IXIC', 'GC=F']

In [3]:
data = yf.download(tickers, group_by='Ticker',start='2010-01-01')

[*********************100%***********************]  11 of 11 completed

In [4]:
data.head()

                JPY=X                                                     \
                 Open       High        Low      Close  Adj Close Volume
Date
2009-12-31  92.430000  93.139999  91.949997  92.910004  92.910004    0.0
2010-01-01  92.940002  93.089996  92.919998  92.919998  92.919998    0.0
2010-01-04  92.760002  93.200996  92.196999  92.495003  92.495003    0.0
2010-01-05  92.470001  92.486000  91.282997  91.584999  91.584999    0.0
2010-01-06  91.550003  92.709999  91.522003  92.356003  92.356003    0.0

                  ^GSPC                                         ...  \
                   Open         High          Low        Close  ...
Date                                                            ...
2009-12-31  1126.599976  1127.640015  1114.810059  1115.099976  ...
2010-01-01          NaN          NaN          NaN          NaN  ...
2010-01-04  1116.560059  1133.869995  1116.560059  1132.989990  ...
2010-01-05  1132.660034  1136.630005  1129.660034  1136.520020  ...
2010-01-06  1135.709961  1139.189941  1133.949951  1137.140015  ...

                  ^IXIC                                            000001.SS  \
                    Low        Close    Adj Close        Volume         Open
Date
2009-12-31  2269.110107  2269.149902  2269.149902  1.237820e+09  3264.998047
2010-01-01          NaN          NaN          NaN           NaN          NaN
2010-01-04  2294.409912  2308.419922  2308.419922  1.931380e+09  3289.750000
2010-01-05  2295.620117  2308.709961  2308.709961  2.367860e+09  3254.468018
2010-01-06  2295.679932  2301.090088  2301.090088  2.253340e+09  3277.517090


                   High          Low        Close    Adj Close    Volume
Date
2009-12-31  3282.210938  3250.025879  3277.138916  3277.138916  116600.0
2010-01-01          NaN          NaN          NaN          NaN       NaN
2010-01-04  3295.279053  3243.319092  3243.760010  3243.760010  109400.0
2010-01-05  3290.511963  3221.461914  3282.178955  3282.178955  126200.0
2010-01-06  3295.867920  3253.043945  3254.215088  3254.215088  123600.0

[5 rows x 66 columns]

code below is referenced from :
https://stackoverflow.com/questions/63107594/how-to-deal-with-multi-level-column-names-downloaded-with-yfinance/63107801#63107801

In [5]:
# d = {idx: gp.xs(idx, level=0, axis=1) for idx, gp in df.groupby(level=0, axis=1)}

In [6]:
data.to_csv('data/stocks.csv')

In [10]:
data

                 JPY=X                                                         \
                  Open        High         Low       Close   Adj Close Volume
Date
2009-12-31   92.430000   93.139999   91.949997   92.910004   92.910004    0.0
2010-01-01   92.940002   93.089996   92.919998   92.919998   92.919998    0.0
2010-01-04   92.760002   93.200996   92.196999   92.495003   92.495003    0.0
2010-01-05   92.470001   92.486000   91.282997   91.584999   91.584999    0.0
2010-01-06   91.550003   92.709999   91.522003   92.356003   92.356003    0.0
...                ...         ...         ...         ...         ...    ...
2021-07-07  110.570000  110.806999  110.402000  110.601997  110.601997    0.0
2021-07-08  110.622002  110.622002  109.535004  110.635002  110.635002    0.0
2021-07-09  109.788002  110.246002  109.766998  109.801003  109.801003    0.0
2021-07-12  110.208000  110.389000  109.982002  110.214996  110.214996    0.0
2021-07-13  110.349998  110.556000  110.169998  110.379997  110.379997    0.0

                  ^GSPC                                         ...  \
                   Open         High          Low        Close  ...
Date                                                            ...
2009-12-31  1126.599976  1127.640015  1114.810059  1115.099976  ...
2010-01-01          NaN          NaN          NaN          NaN  ...
2010-01-04  1116.560059  1133.869995  1116.560059  1132.989990  ...
2010-01-05  1132.660034  1136.630005  1129.660034  1136.520020  ...
2010-01-06  1135.709961  1139.189941  1133.949951  1137.140015  ...
...                 ...          ...          ...          ...  ...
2021-07-07  4351.009766  4361.879883  4329.790039  4358.129883  ...
2021-07-08  4321.069824  4330.879883  4289.370117  4320.819824  ...
2021-07-09  4329.379883  4371.600098  4329.379883  4369.549805  ...
2021-07-12  4372.410156  4386.680176  4364.029785  4384.629883  ...
2021-07-13  4381.069824  4392.370117  4376.839844  4390.000000  ...

                   ^IXIC                                            \
                     Low         Close     Adj Close        Volume
Date
2009-12-31   2269.110107   2269.149902   2269.149902  1.237820e+09
2010-01-01           NaN           NaN           NaN           NaN
2010-01-04   2294.409912   2308.419922   2308.419922  1.931380e+09
2010-01-05   2295.620117   2308.709961   2308.709961  2.367860e+09
2010-01-06   2295.679932   2301.090088   2301.090088  2.253340e+09
...                  ...           ...           ...           ...
2021-07-07  14580.790039  14665.059570  14665.059570  4.582030e+09
2021-07-08  14371.589844  14559.780273  14559.780273  4.550600e+09
2021-07-09  14552.259766  14701.919922  14701.919922  3.809040e+09
2021-07-12  14672.629883  14733.240234  14733.240234  3.864500e+09
2021-07-13  14696.144531  14796.900391  14796.900391  2.094763e+09

              000001.SS                                                      \
                   Open         High          Low        Close    Adj Close
Date
2009-12-31  3264.998047  3282.210938  3250.025879  3277.138916  3277.138916
2010-01-01          NaN          NaN          NaN          NaN          NaN
2010-01-04  3289.750000  3295.279053  3243.319092  3243.760010  3243.760010
2010-01-05  3254.468018  3290.511963  3221.461914  3282.178955  3282.178955
2010-01-06  3277.517090  3295.867920  3253.043945  3254.215088  3254.215088
...                 ...          ...          ...          ...          ...
2021-07-07  3508.590088  3557.879883  3504.469971  3553.719971  3553.719971
2021-07-08  3557.219971  3558.679932  3521.060059  3525.500000  3525.500000
2021-07-09  3512.229980  3529.310059  3485.050049  3524.090088  3524.090088
2021-07-12  3545.199951  3565.030029  3527.389893  3547.840088  3547.840088
2021-07-13  3547.589600  3567.481201  3542.815430  3566.522461  3566.522461


                  Volume
Date
2009-12-31  1.166000e+05
2010-01-01           NaN
2010-01-04  1.094000e+05
2010-01-05  1.262000e+05
2010-01-06  1.236000e+05
...                  ...
2021-07-07  3.188000e+05
2021-07-08  3.509000e+05
2021-07-09  3.499000e+05
2021-07-12  4.036000e+05
2021-07-13  1.881933e+09

[3009 rows x 66 columns]